project:
  type: website
  render:
    - /slides/introduction.qmd
    - /slides/wrangling.qmd
    - /slides/ggplot.qmd
    - /slides/geospatial.qmd
    - index.qmd
    - "/cards/**/*.qmd"
    - "/exercises/**/*.qmd"

website:
  title: "Introduction aux méthodes quantitatives avec {{< fa brands r-project >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/r-base.html
        text: Introduction
      - href: exercises/r-wrangling.html
        text: Manipulation
      - icon: github
        href: https://github.com/linogaliana/r-geographie
    background: "#802a03"
  twitter-card:
    image: /cards/version-light/baby.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true

author: Lino Galiana


#knitr:
#  opts_chunk:
#    out.width: "90%"
    
    