project:
  type: website
  render:
    - /slides/introduction.qmd
    - index.qmd
    - "/cards/**/*.qmd"

website:
  title: "Introduction aux méthodes quantitatives avec {{< fa brands r-project >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/introduction.html
        text: Introduction
    background: "#802a03"
  twitter-card:
    image: /cards/version-light/baby.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

