name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-rstudio:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
