name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-rstudio:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure safe.directory  # Workaround for actions/checkout#760
        run: git config --global --add safe.directory /__w/r-geographie/r-geographie
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      - name: Render website
        run: |
          quarto render --to html
      - name: Publish to Pages
        run: |
          git config --global user.email quarto-github-actions-publish@example.com
          git config --global user.name "Quarto GHA Workflow Runner"
          quarto publish gh-pages . --no-render --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
